import type { Source } from "./types";

export const SOURCES: Source[] = [
  // AI & Tech
  {
    id: "techcrunch",
    name: "TechCrunch",
    url: "https://techcrunch.com",
    feed: "https://techcrunch.com/feed/",
    topic: "ai",
    homepage: "https://techcrunch.com",
  },
  {
    id: "theverge",
    name: "The Verge",
    url: "https://www.theverge.com",
    feed: "https://www.theverge.com/rss/index.xml",
    topic: "ai",
    homepage: "https://www.theverge.com",
  },
  {
    id: "hackernews",
    name: "Hacker News",
    url: "https://news.ycombinator.com",
    feed: "https://hnrss.org/frontpage",
    topic: "ai",
    homepage: "https://news.ycombinator.com",
  },
  {
    id: "arstechnica",
    name: "Ars Technica",
    url: "https://arstechnica.com",
    feed: "https://feeds.arstechnica.com/arstechnica/index",
    topic: "ai",
    homepage: "https://arstechnica.com",
  },
  {
    id: "mit-tech-review",
    name: "MIT Tech Review",
    url: "https://www.technologyreview.com",
    feed: "https://www.technologyreview.com/feed/",
    topic: "ai",
    homepage: "https://www.technologyreview.com",
  },

  // Finance & Markets
  {
    id: "yahoo-finance",
    name: "Yahoo Finance",
    url: "https://finance.yahoo.com",
    feed: "https://finance.yahoo.com/news/rssindex",
    topic: "finance",
    homepage: "https://finance.yahoo.com",
  },
  {
    id: "marketwatch",
    name: "MarketWatch",
    url: "https://www.marketwatch.com",
    feed: "https://feeds.content.dowjones.io/public/rss/mw_topstories",
    topic: "finance",
    homepage: "https://www.marketwatch.com",
  },
  {
    id: "cnbc",
    name: "CNBC",
    url: "https://www.cnbc.com",
    feed: "https://www.cnbc.com/id/100003114/device/rss/rss.html",
    topic: "finance",
    homepage: "https://www.cnbc.com",
  },
  {
    id: "investing",
    name: "Investing.com",
    url: "https://www.investing.com",
    feed: "https://www.investing.com/rss/news.rss",
    topic: "finance",
    homepage: "https://www.investing.com",
  },

  // Crypto
  {
    id: "coindesk",
    name: "CoinDesk",
    url: "https://www.coindesk.com",
    feed: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    topic: "crypto",
    homepage: "https://www.coindesk.com",
  },
  {
    id: "theblock",
    name: "The Block",
    url: "https://www.theblock.co",
    feed: "https://www.theblock.co/rss.xml",
    topic: "crypto",
    homepage: "https://www.theblock.co",
  },
  {
    id: "decrypt",
    name: "Decrypt",
    url: "https://decrypt.co",
    feed: "https://decrypt.co/feed",
    topic: "crypto",
    homepage: "https://decrypt.co",
  },
  {
    id: "bitcoin-magazine",
    name: "Bitcoin Magazine",
    url: "https://bitcoinmagazine.com",
    feed: "https://bitcoinmagazine.com/.rss/full/",
    topic: "crypto",
    homepage: "https://bitcoinmagazine.com",
  },
  {
    id: "cointelegraph",
    name: "Cointelegraph",
    url: "https://cointelegraph.com",
    feed: "https://cointelegraph.com/rss",
    topic: "crypto",
    homepage: "https://cointelegraph.com",
  },

  // Politics
  {
    id: "bbc-world",
    name: "BBC World",
    url: "https://www.bbc.com",
    feed: "http://feeds.bbci.co.uk/news/world/rss.xml",
    topic: "politics",
    homepage: "https://www.bbc.com/news/world",
  },
  {
    id: "aljazeera",
    name: "Al Jazeera",
    url: "https://www.aljazeera.com",
    feed: "https://www.aljazeera.com/xml/rss/all.xml",
    topic: "politics",
    homepage: "https://www.aljazeera.com",
  },
  {
    id: "reuters-world",
    name: "Reuters World",
    url: "https://www.reuters.com",
    feed: "https://news.google.com/rss/search?q=when:24h+site:reuters.com&hl=en-US&gl=US&ceid=US:en",
    topic: "politics",
    homepage: "https://www.reuters.com/world",
  },
  {
    id: "ap-top",
    name: "AP News",
    url: "https://apnews.com",
    feed: "https://news.google.com/rss/search?q=when:24h+site:apnews.com&hl=en-US&gl=US&ceid=US:en",
    topic: "politics",
    homepage: "https://apnews.com",
  },

  // Business
  {
    id: "bloomberg",
    name: "Bloomberg",
    url: "https://www.bloomberg.com",
    feed: "https://news.google.com/rss/search?q=when:24h+site:bloomberg.com&hl=en-US&gl=US&ceid=US:en",
    topic: "business",
    homepage: "https://www.bloomberg.com",
  },
  {
    id: "wsj",
    name: "Wall Street Journal",
    url: "https://www.wsj.com",
    feed: "https://news.google.com/rss/search?q=when:24h+site:wsj.com&hl=en-US&gl=US&ceid=US:en",
    topic: "business",
    homepage: "https://www.wsj.com",
  },
  {
    id: "ft",
    name: "Financial Times",
    url: "https://www.ft.com",
    feed: "https://news.google.com/rss/search?q=when:24h+site:ft.com&hl=en-US&gl=US&ceid=US:en",
    topic: "business",
    homepage: "https://www.ft.com",
  },

  // Science
  {
    id: "sciencedaily",
    name: "ScienceDaily",
    url: "https://www.sciencedaily.com",
    feed: "https://www.sciencedaily.com/rss/top.xml",
    topic: "science",
    homepage: "https://www.sciencedaily.com",
  },
  {
    id: "nature",
    name: "Nature",
    url: "https://www.nature.com",
    feed: "https://www.nature.com/nature.rss",
    topic: "science",
    homepage: "https://www.nature.com",
  },
  {
    id: "newscientist",
    name: "New Scientist",
    url: "https://www.newscientist.com",
    feed: "https://www.newscientist.com/feed/home/",
    topic: "science",
    homepage: "https://www.newscientist.com",
  },
];
